version: '3.8'
networks:
  app-network:

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - 8080:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    networks:
      - app-network
    restart: always
    depends_on:
      - django

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.telegram_bot
    networks:
      - app-network
    restart: always
    env_file:
      - ./.env
    depends_on:
      - django
